#!/bin/sh

echo "git diff:"
CURRENT_BRANCH_NAME=`git branch --show-current`
FILES=`git diff --stat --cached --name-only origin/$CURRENT_BRANCH_NAME`
FILES_TO_CHANGE=`echo $FILES | egrep "*\.cpp|*\.ino|*\.h"`
if [ -z "${FILES_TO_CHANGE}" ]; then
  echo "[astyle]: No source files (.cpp .ino .h) changed. Nothing to format"
else
  echo "[astyle]: files to format are:"
  echo "$FICHEROS"
  echo "[astyle]: Running..."
  astyle --options=./.astylerc ${FICHEROS}
  echo "[astyle]: All formatted"
fi
